### ISSUE TITLE
Documentation issue: connecting to Discord client?

### ISSUE THREAD

**Issue by rmenessec** [FayneAldan/SVRichPresence#3]
The release notes and description don't seem to cover this question: does the Discord client have to be running _before_ SDV starts, or will the mod periodically retry connecting? Will reloading the config (F5) cause the mod to attempt to connect to the Discord client?

Thanks!

**Comment by FayneAldan** [comment]
This works however the Discord Rich Presence API works, which I think will periodically retry connecting when it fails to connect or disconnects. Reloading the config will not reconnect the mod.

**Comment by rmenessec** [comment]
Understood. Thanks!
